# Generated by Django 2.0.2 on 2019-02-05 18:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('about', models.TextField(blank=True)),
                ('problem', models.TextField(blank=True)),
                ('problem_solve', models.TextField(blank=True)),
                ('how_problem_solve', models.TextField(blank=True)),
                ('project_cost', models.IntegerField(blank=True, null=True)),
                ('purchase_place', models.TextField(blank=True)),
                ('tools_usage', models.TextField(blank=True)),
                ('the_end', models.TextField(blank=True)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('active', models.BooleanField(default=True)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('step_title', models.CharField(blank=True, max_length=100)),
                ('step_photo', models.FileField(blank=True, upload_to='media')),
                ('step_photo_caption', models.CharField(blank=True, max_length=100)),
                ('step_content', models.TextField(blank=True)),
                ('code', models.FileField(blank=True, upload_to='document')),
                ('step_assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes_app.Note')),
            ],
        ),
    ]
