# Generated by Django 2.1.3 on 2018-11-26 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='titel',
            new_name='title',
        ),
    ]
