# Generated by Django 2.0.2 on 2019-02-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_auto_20190206_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='step_code',
            field=models.FileField(blank=True, upload_to='document'),
        ),
    ]
