# Generated by Django 2.1.3 on 2018-11-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0003_auto_20181126_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
