# Generated by Django 2.0.2 on 2019-02-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0003_steps_step_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='fin_vid',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
