# Generated by Django 2.1.3 on 2018-11-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0004_auto_20181126_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='استخدمت_المكن_فين',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='tags',
            new_name='الاشارات',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='title',
            new_name='العنوان',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='user',
            new_name='المستخدم',
        ),
        migrations.AddField(
            model_name='note',
            name='الكود',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='note',
            name='المقدمة',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='note',
            name='تكلفة_المشروع',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='note',
            name='خطوات_المشروع',
            field=models.TextField(blank=True),
        ),
    ]
