# Generated by Django 2.0.2 on 2019-02-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0004_auto_20190206_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='code_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='steps',
            name='step_code_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
