# Generated by Django 2.0.2 on 2019-04-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0005_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='vid',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
