# Generated by Django 2.1.3 on 2018-11-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0005_auto_20181126_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='ارفع_صورة',
            field=models.ImageField(default='', upload_to='notes-img'),
            preserve_default=False,
        ),
    ]
