# Generated by Django 2.0.2 on 2019-04-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0006_auto_20190403_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='diff',
            field=models.TextField(blank=True),
        ),
    ]
