# Generated by Django 2.0.2 on 2018-12-03 18:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0006_note_ارفع_صورة'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='استخدمت_المكن_فين',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='الكود',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='المقدمة',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='تكلفة_المشروع',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='خطوات_المشروع',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
