# Generated by Django 2.0.2 on 2018-12-03 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0007_auto_20181203_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='المستخدم',
            new_name='user',
        ),
    ]
