# Generated by Django 2.0.2 on 2018-12-04 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0008_auto_20181203_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user',
            new_name='المستخدم',
        ),
    ]
