# Generated by Django 2.0.2 on 2018-12-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0010_auto_20181204_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='استخدمت_المكن_فين',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='الكود',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='المقدمة',
            new_name='intro',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='تكلفة_المشروع',
            new_name='steps',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='الاشارات',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='العنوان',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='خطوات_المشروع',
            new_name='tools',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='ارفع_صورة',
            new_name='upload_photo',
        ),
    ]
