# Generated by Django 2.0.2 on 2018-12-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0011_auto_20181206_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='upload_photo',
            field=models.ImageField(blank=True, upload_to='notes-img'),
        ),
    ]
