# Generated by Django 2.0.2 on 2018-12-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0012_auto_20181206_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='upload_file',
            field=models.FileField(blank=True, upload_to='notes-files'),
        ),
    ]
