# Generated by Django 2.0.2 on 2018-12-09 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0015_remove_note_upload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='upload_photo',
        ),
        migrations.AddField(
            model_name='note',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='notes-img'),
            preserve_default=False,
        ),
    ]
