# Generated by Django 2.0.2 on 2018-12-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0016_auto_20181209_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='document',
            field=models.FileField(blank=True, upload_to='document'),
        ),
    ]
