# Generated by Django 2.0.2 on 2018-12-13 18:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0017_note_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='cost',
            new_name='أماكن_استخدام_المكن_والأدوات',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='intro',
            new_name='أماكن_شراء_المكونات_والادوات',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='steps',
            new_name='التكلفة_الشاملة_للمشروع',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='tools',
            new_name='التوصيلة_الكهربية',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='title',
            new_name='العنوان',
        ),
        migrations.RemoveField(
            model_name='note',
            name='document',
        ),
        migrations.AddField(
            model_name='note',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='notes-img'),
        ),
        migrations.AddField(
            model_name='note',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='notes-img'),
        ),
        migrations.AddField(
            model_name='note',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='notes-img'),
        ),
        migrations.AddField(
            model_name='note',
            name='photo4',
            field=models.ImageField(blank=True, upload_to='notes-img'),
        ),
        migrations.AddField(
            model_name='note',
            name='photo5',
            field=models.ImageField(blank=True, upload_to='notes-img'),
        ),
        migrations.AddField(
            model_name='note',
            name='photo6',
            field=models.ImageField(blank=True, upload_to='notes-img'),
        ),
        migrations.AddField(
            model_name='note',
            name='photo7',
            field=models.ImageField(blank=True, upload_to='notes-img'),
        ),
        migrations.AddField(
            model_name='note',
            name='photo8',
            field=models.ImageField(blank=True, upload_to='notes-img'),
        ),
        migrations.AddField(
            model_name='note',
            name='photo9',
            field=models.ImageField(blank=True, upload_to='notes-img'),
        ),
        migrations.AddField(
            model_name='note',
            name='المشكلة',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='note',
            name='شكل_الدائرة_بعد_التوصيل',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='note',
            name='كيف_قمت_بتطبيق_الحل',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='note',
            name='ما_حل_المشكلة',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='note',
            name='هل_واجهت_مشاكل_في_التوصيل',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='code',
            field=models.FileField(blank=True, upload_to='document'),
        ),
    ]
