# Generated by Django 2.0.2 on 2019-01-24 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0019_note_النهاية'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='العنوان',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='note',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='note',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='note',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='note',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='note',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='note',
            name='photo5',
        ),
        migrations.RemoveField(
            model_name='note',
            name='photo6',
        ),
        migrations.RemoveField(
            model_name='note',
            name='photo7',
        ),
        migrations.RemoveField(
            model_name='note',
            name='photo8',
        ),
        migrations.RemoveField(
            model_name='note',
            name='photo9',
        ),
        migrations.RemoveField(
            model_name='note',
            name='أماكن_استخدام_المكن_والأدوات',
        ),
        migrations.RemoveField(
            model_name='note',
            name='أماكن_شراء_المكونات_والادوات',
        ),
        migrations.RemoveField(
            model_name='note',
            name='التكلفة_الشاملة_للمشروع',
        ),
        migrations.RemoveField(
            model_name='note',
            name='التوصيلة_الكهربية',
        ),
        migrations.RemoveField(
            model_name='note',
            name='المشكلة',
        ),
        migrations.RemoveField(
            model_name='note',
            name='النهاية',
        ),
        migrations.RemoveField(
            model_name='note',
            name='شكل_الدائرة_بعد_التوصيل',
        ),
        migrations.RemoveField(
            model_name='note',
            name='كيف_قمت_بتطبيق_الحل',
        ),
        migrations.RemoveField(
            model_name='note',
            name='ما_حل_المشكلة',
        ),
        migrations.RemoveField(
            model_name='note',
            name='هل_واجهت_مشاكل_في_التوصيل',
        ),
    ]
