# Generated by Django 2.0.2 on 2019-01-31 13:28

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0022_auto_20190131_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='documentation',
        ),
        migrations.AddField(
            model_name='note',
            name='content',
            field=django_bleach.models.BleachField(blank=True),
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
