# Generated by Django 2.0.2 on 2019-01-31 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0023_auto_20190131_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
    ]
