# Generated by Django 2.0.2 on 2019-01-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0024_remove_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='step_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
