# Generated by Django 2.0.2 on 2019-01-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0025_note_step_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_title', models.CharField(blank=True, max_length=100)),
                ('step_photo', models.FileField(blank=True, upload_to='media')),
                ('step_photo_caption', models.CharField(blank=True, max_length=100)),
                ('step_content', models.TextField(blank=True)),
            ],
        ),
    ]
