# Generated by Django 2.0.2 on 2019-02-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0026_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_title', models.CharField(blank=True, max_length=100)),
                ('step_photo', models.FileField(blank=True, upload_to='media')),
                ('step_photo_caption', models.CharField(blank=True, max_length=100)),
                ('step_content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_title', models.CharField(blank=True, max_length=100)),
                ('step_photo', models.FileField(blank=True, upload_to='media')),
                ('step_photo_caption', models.CharField(blank=True, max_length=100)),
                ('step_content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_title', models.CharField(blank=True, max_length=100)),
                ('step_photo', models.FileField(blank=True, upload_to='media')),
                ('step_photo_caption', models.CharField(blank=True, max_length=100)),
                ('step_content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_title', models.CharField(blank=True, max_length=100)),
                ('step_photo', models.FileField(blank=True, upload_to='media')),
                ('step_photo_caption', models.CharField(blank=True, max_length=100)),
                ('step_content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_title', models.CharField(blank=True, max_length=100)),
                ('step_photo', models.FileField(blank=True, upload_to='media')),
                ('step_photo_caption', models.CharField(blank=True, max_length=100)),
                ('step_content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_title', models.CharField(blank=True, max_length=100)),
                ('step_photo', models.FileField(blank=True, upload_to='media')),
                ('step_photo_caption', models.CharField(blank=True, max_length=100)),
                ('step_content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_title', models.CharField(blank=True, max_length=100)),
                ('step_photo', models.FileField(blank=True, upload_to='media')),
                ('step_photo_caption', models.CharField(blank=True, max_length=100)),
                ('step_content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_title', models.CharField(blank=True, max_length=100)),
                ('step_photo', models.FileField(blank=True, upload_to='media')),
                ('step_photo_caption', models.CharField(blank=True, max_length=100)),
                ('step_content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_title', models.CharField(blank=True, max_length=100)),
                ('step_photo', models.FileField(blank=True, upload_to='media')),
                ('step_photo_caption', models.CharField(blank=True, max_length=100)),
                ('step_content', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Steps',
            new_name='Step1',
        ),
    ]
