# Generated by Django 2.0.2 on 2019-02-04 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0029_steps_step_assign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='components',
            new_name='about',
        ),
        migrations.RemoveField(
            model_name='note',
            name='active',
        ),
        migrations.RemoveField(
            model_name='note',
            name='code',
        ),
        migrations.RemoveField(
            model_name='note',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='note',
            name='created',
        ),
        migrations.RemoveField(
            model_name='note',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='note',
            name='how_problem_solved',
        ),
        migrations.RemoveField(
            model_name='note',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='note',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='note',
            name='problem_solve',
        ),
        migrations.RemoveField(
            model_name='note',
            name='purchase_places',
        ),
        migrations.RemoveField(
            model_name='note',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='note',
            name='step_title',
        ),
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='note',
            name='the_end',
        ),
        migrations.RemoveField(
            model_name='note',
            name='tools_using',
        ),
    ]
