# Generated by Django 2.0.2 on 2019-02-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0030_auto_20190204_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
