# Generated by Django 2.0.2 on 2019-02-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0031_note_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='code',
            field=models.FileField(blank=True, upload_to='document'),
        ),
    ]
