# Generated by Django 2.0.2 on 2019-02-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0032_steps_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
