# Generated by Django 2.0.2 on 2018-12-02 15:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('الاسم_الاول', models.CharField(blank=True, max_length=100)),
                ('الاسم_الاخير', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField()),
                ('headline', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('الصورة_الشخصية', models.ImageField(upload_to='profile_img')),
                ('تاريخ_التسجيل', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('المستخدم', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
