# Generated by Django 2.0.2 on 2018-12-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181202_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='الاسم_الاخير',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='الصورة_الشخصية',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='تاريخ_التسجيل',
            new_name='join_date',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='الاسم_الاول',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='المستخدم',
            new_name='user',
        ),
    ]
