# Generated by Django 2.0.2 on 2018-12-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181202_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='الاسم_الاخير',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='الاسم_الاول',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='img',
            new_name='الصورة_الشخصية',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='المستخدم',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='join_date',
            new_name='تاريخ_التسجيل',
        ),
    ]
