# Generated by Django 2.0.2 on 2018-12-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20181202_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='الصورة_الشخصية',
            field=models.ImageField(blank=True, upload_to='profile_img'),
        ),
    ]
