# Generated by Django 2.0.2 on 2018-12-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20181204_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='الصورة_الشخصية',
            field=models.ImageField(upload_to='profile_img'),
        ),
    ]
